#!/bin/bash

set -e

CATALINA_HOME='/var/lib/tomcat9'

TEMP_STAGING_DIR='/tmp/codedeploy-deployment-staging-area'
WAR_STAGED_LOCATION="$TEMP_STAGING_DIR/hello-1.0.war"

# Copy the WAR file to the webapps directory
cp $WAR_STAGED_LOCATION $CATALINA_HOME/webapps

systemctl restart tomcat9
